### ISSUE TITLE
Add a README.md file

### ISSUE THREAD

**Issue by Prajwalu-13** [Prajwalu-13/weather-app#1]
Add a suitable README.md file

**Comment by SaarthakMaini** [comment]
If possible, I would like to work on this issue, under Hacktoberfest.

Thank you!

**Comment by ujjwal-11103** [comment]
I have a quite experience in creating README.md file 
I request you to assign it to me

**Comment by SaarthakMaini** [comment]
Closing https://github.com/Prajwalu-13/weather-app/pull/6 

Please provide feedback on why my Pull Request was ignored?
